routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use App\Http\Controllers\Wall\WallController as Wall;
use App\Http\Controllers\Wall\NewsController as News;
use App\Http\Controllers\Account\AuthenticationController as Authentication;
use App\Http\Controllers\Account\AccountController as Account;
use App\Mail\VerifyAccount;
use App\Models\User;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middleware' => 'verifyingAccount'], function() {

    Route::resource('/', Wall::class);

    Route::resource('/news', News::class);

    Route::get('/profile', [Account::class, 'indexProfile'])->name('profile');

    Route::put('/profile-edit', [Account::class, 'updateProfile'])->name('update.profile');

});

Route::group(['prefix' => '/register', 'middleware' => 'guest'], function() {

    Route::get('/', [Authentication::class, 'indexRegister'])->name('register');

    Route::post('/', [Authentication::class, 'register'])->name('register.store');

});

Route::group(['prefix' => '/login', 'middleware' => 'guest'], function() {

    Route::get('/', [Authentication::class, 'indexLogin'])->name('login');

    Route::post('/', [Authentication::class, 'login'])->name('login.store');

});

Route::group(['middleware' => 'auth'], function() {
    
    Route::get('/verifying-account', function() {
        if (Auth::user()->verified_at == null) {
            return view('Apps.Public.Account.VerifyingAccount');
        } else {
            return redirect()->route('index');
        }
        
    })->name('verifying-account');

    Route::get('/send-verify', function() {
        $email    = Auth::user()->email;
        $username = Auth::user()->username;
        Mail::to($email)->send(new VerifyAccount($username, $email));
        return redirect()->route('verifying-account');
    })->name('send.verify');

    Route::get('/token={token}', function($token) {
        if (Auth::user()->token_verification == $token) {
            User::find(Auth::id())->update([
                'verified_at' => date("Y-m-d H:i:s"),
            ]);
            return redirect()->route('index');
        }
    });

    Route::get('/logout', function() {
        Auth::logout();
        return redirect()->route('index');
    })->name('logout');

});

app/Http/Controllers/Account/AccountController.php
<?php

namespace App\Http\Controllers\Account;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

use Auth, Storage;
use App\Models\User;

class AccountController extends Controller
{
    public function indexProfile()
    {
        return view('Apps.Public.Account.Profile');
    }

    public function updateProfile(Request $request)
    {
        $this->validate($request, [
            'profile_pic' => 'image',
            'username' => 'required',
            'email' => 'required',
        ]);
        
        $profile_pic = $request->profile_pic;
        $username = $request->username;
        $email = $request->email;
        $profile_pic_name = '8_site'.date('Y-m-d-H-i-s').'.png';

        $Profile = User::findOrFail(Auth::id());

        if ($request->hasFile('profile_pic')) {
            Storage::disk('storage')->putFileAs('Image', $profile_pic, $profile_pic_name);
            $Profile->update([
                'profile_picture' => $profile_pic_name,
            ]);
        }

        if ($Profile->email != $email) {
            $Profile->update([
                'verified_at' => null,
            ]);
        }

        $Profile->update([
            'username' => $username,
            'email' => $email,
        ]);

        return redirect()->back();
    }
}

app/Http/Controllers/Account/AuthenticationController.php
<?php

namespace App\Http\Controllers\Account;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

use Auth;
use Hash;
use Mail;
use App\Models\User;
use App\Mail\VerifyAccount;

class AuthenticationController extends Controller
{   
    public function indexLogin()
    {
        return view('Apps.Public.Account.Login');
    }

    public function login(Request $request)
    {
        $this->validate($request, [
            'email'    => 'required|exists:users',
            'password' => 'required',
        ]);

        $email = $request->email;
        $password = $request->password;

        $user = User::where('email', $email)->first();

        if (Auth::attempt(['email' => $email, 'password' => $password])) {
            $request->session()->regenerate();
            return redirect()->route('index');
        } else {
            return redirect()->back()->with('invalidLogin', 'Something wrong here');
        }
    }

    public function indexRegister()
    {
        return view('Apps.Public.Account.Register');
    }

    public function register(Request $request)
    {
        $messages = [
            'username.required'  => 'Username is required you know',
            'email.required'     => 'Email is required you know',
            'email.unique'       => 'Email already used, <u>'.$request->email.'</u> is that you?',
            'password.required'  => 'Password is required you know',
            'password.confirmed' => 'Please confirm your Password',
        ];

        $this->validate($request, [
            'username' => 'required',
            'email'    => 'required|unique:users',
            'password' => 'required|confirmed',
        ], $messages);

        $username           = $request->username;
        $email              = $request->email;
        $password           = Hash::make($request->password);

        $user = User::create([
            'username'           => $username,
            'email'              => $email,
            'password'           => $password,
        ]);
        
        Mail::to($email)->send(new VerifyAccount($username, $email));

        Auth::login($user);
        
        return redirect()->route('verifying-account');
    }

    public function indexResetPassword()
    {
        
    }

    public function resetPassword()
    {
        
    }

    public function indexDeleteAccount()
    {
        # code...
    }

    public function deleteAccount(Request $request)
    {
        
    }
}

resources/views/Apps/Public/Account/Login.blade.php
@extends('Layouts.Public.Master')

@section('Content')
<!-- Content -->
<div class="ungap marg5 padd5">

    <!-- Login -->
    @if ($errors->any())
    <div class="card-alert-lava marg2-t">
        @foreach ($errors->all() as $error)
            <li>{{ $error }}</li>
        @endforeach
    </div>
    @elseif (session('invalidLogin'))
    <div class="card-alert-lava marg2-t">
        <li>{{ session('invalidLogin') }}</li>
    </div>
    @endif
    <h1>Login</h1>
    <div class="divider-black"></div>
    <form method="POST" action="{{route('login.store')}}">
        @csrf
        <div class="raw">
            <div class="cal12">
                <div class="group-form">
                    <label for="email">Email</label>
                    <input id="email" name="email" type="email" placeholder="Email">
                </div>
            </div>
            <div class="cal12">
                <div class="group-form">
                    <label for="password">Password</label>
                    <input id="password" name="password" type="password" placeholder="Password">
                </div>
            </div>
        </div>
        <div class="padd1">
            <button type="submit" class="btn btn-grass btn-box t-size2">Login</button>
        </div>
    </form>

    <!-- Login End -->
</div>

<!-- Content End -->
@endsection

@push('Javascript')

@endpush

resources/views/Apps/Public/Account/Profile.blade.php
@extends('Layouts.Public.Master')

@section('Content')
<!-- Content -->

<div class="ungap">
    <div class="raw">
        <div class="cal2">
            <div class="sidebang">
                <ul>
                    <li>
                        <a class="side-i" href="#1"><i class="fi-xnsrxm-chevron-solid"></i> Account</a>
                    </li>
                    <li>
                        <a class="side-i" href="{{route('news.create')}}"><i class="fi-xnsrxm-chevron-solid"></i>
                            Post</a>
                    </li>
                </ul>
            </div>
        </div>
        <div class="calauto padd1">
            <!-- Post List -->
            <h1>Post</h1>
            <div class="divider-black"></div>
            <div class="raw">
                @if (RDev::CountPost() != 0)
                @foreach (RDev::News(5)->where('author', Auth::id()) as $news)
                <div class="cal12">
                    <div class="card-box">
                        <div class="card-box-body-white no-img">
                            <div class="card-title">
                                <div class="raw">
                                    <div class="calauto">
                                        <a href="{{route('news.show', [$news->slug])}}"
                                            class="t-size3 t-black">{{$news->title}}</a>
                                    </div>
                                    <div class="cal1 t-right">
                                        <form action="{{route('news.destroy', ['news'=>$news->uuid])}}" method="POST">
                                            @csrf
                                            @method('DELETE')
                                            <a href="javascript:void(0)" class="t-black"><i class="fi-xnsuxl-trash-bin"
                                                    onclick="this.closest('form').submit()"></i></a>
                                        </form>
                                    </div>
                                </div>
                            </div>
                            <p class="t-black t-center">
                                {!!$news->content!!}
                            </p>
                            <div class="raw t-size1">
                                <div class="cal5 t-left">
                                    <p class="t-black">1 Days ago</p>
                                </div>
                                <div class="cal7 t-right">
                                    <a href="{{route('news.show', [$news->slug])}}" class="t-black">Baca
                                        Selengkapnya</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                @endforeach
                @endif
            </div>
            {{RDev::News(5)->links('vendor.pagination.bootstrap-4')}}
            <!-- Post List End -->
            <!-- Account Detail -->
            <h1>Account</h1>
            <div class="divider-black"></div>
            <div id="dataprofile">
                <div class="raw">
                    <div class="cal12">
                        <div class="group-form">
                            <label>Profile Picture :</label>
                            <div class="img-size3 img-circ img-center img-prof"
                                style="background-image: url({{asset('Storage/Image/'.Auth::user()->profile_picture)}});">
                            </div>
                            <!-- <img src="asset/ricky.jpg" class="img-size1 img-roun margauto-r margauto-l"> -->
                        </div>
                    </div>
                    <div class="cal6">
                        <div class="group-form">
                            <label>Username :</label>
                            <p>{{Auth::user()->username}}</p>
                        </div>
                    </div>
                    <div class="cal6">
                        <div class="group-form">
                            <label>Email :</label>
                            <p>{{Auth::user()->email}}</p>
                        </div>
                    </div>
                </div>
            </div>
            <form id="formedit" action="{{route('update.profile')}}" method="POST" enctype="multipart/form-data" style="display: none;">
                @csrf
                @method('PUT')
                <div class="raw">
                    <div class="cal12">
                        <div class="group-form">
                            <label>Profile Picture :</label>
                            <input id="profile_pic" name="profile_pic" type="file" placeholder="Profile Pic" accept="image/*">
                        </div>
                    </div>
                    <div class="cal6">
                        <div class="group-form">
                            <label>Username :</label>
                            <input id="username" name="username" type="text" placeholder="Username"
                                value="{{Auth::user()->username}}">
                        </div>
                    </div>
                    <div class="cal6">
                        <div class="group-form">
                            <label>Email :</label>
                            <input id="email" name="email" type="email" placeholder="Email"
                                value="{{Auth::user()->email}}">
                        </div>
                    </div>
                    <div class="cal12">
                        <button type="submit" class="btn btn-water btn-box t-size2">Post</button>
                        <button type="button" class="btn btn-lava btn-box t-size2"
                            onclick="closeEditForm()">Close</button>
                    </div>
                </div>
            </form>
            <div class="padd1">
                <button id="edit" type="button" class="btn btn-water btn-box t-size2" onclick="editForm()">Edit</button>
            </div>
            <!-- Account Detail end -->

        </div>
    </div>
</div>

<!-- Content End -->
@endsection

@push('Javascript')

<script>
    function editForm() {
        document.getElementById("formedit").style.display = "block"
        document.getElementById("dataprofile").style.display = "none"
        document.getElementById("edit").style.display = "none"
    }

    function closeEditForm() {
        document.getElementById("formedit").style.display = "none"
        document.getElementById("dataprofile").style.display = "block"
        document.getElementById("edit").style.display = "block"
    }
</script>

@endpush

resources/views/Apps/Public/Account/Register.blade.php
@extends('Layouts.Public.Master')

@section('Content')
<!-- Content -->

<div class="ungap marg5 padd5">
    <!-- Register -->
    <h1>Register</h1>
    <div class="divider-black"></div>
    <form method="POST" action="{{route('register.store')}}">
        @csrf
        <div class="raw">
            @if ($errors->any())
            <div class="cal12 padd2">
                <div class="card-alert-lava">
                    <ul class="padd2-l">
                        @foreach ($errors->all() as $error)
                        <li>{!!$error!!}</li>
                        @endforeach
                    </ul>
                </div>
            </div>
            @endif
            <div class="cal6">
                <div class="group-form">
                    <label for="username">Username <span class="req">*</span></label>
                    <input id="username" name="username" @error('username') class="lava-form-border" @enderror
                        type="text" placeholder="Username" value="{{old('username')}}">
                </div>
            </div>
            <div class="cal6">
                <div class="group-form">
                    <label for="email">Email <span class="req">*</span></label>
                    <input id="email" name="email" @error('email') class="lava-form-border" @enderror type="email"
                        placeholder="Email" value="{{old('email')}}">
                </div>
            </div>
            <div class="cal6">
                <div class="group-form">
                    <label for="password">Password <span class="req">*</span></label>
                    <input id="password" name="password" @error('password') class="lava-form-border" @enderror
                        type="password" placeholder="Password">
                </div>
            </div>
            <div class="cal6">
                <div class="group-form">
                    <label for="re-password">Re-Password <span class="req">*</span></label>
                    <input id="re-password" name="password_confirmation" @error('password') class="lava-form-border"
                        @enderror type="password" placeholder="Re-Password">
                </div>
            </div>
        </div>
        <div class="padd1">
            <button type="submit" class="btn btn-grass btn-box t-size2">Register</button>
        </div>
    </form>
    <!-- Register End -->
</div>

<!-- Content End -->
@endsection

@push('Javascript')

@endpush

resources/views/Apps/Public/Account/VerifyingAccount.blade.php
@extends('Layouts.Public.Master')

@section('Content')
<!-- Content -->

<div class="ungap marg5 padd5">

    {{-- Alert Card --}}

    <div class="card-alert-water">
        <p>
            Thanks for register on our blog, before that you need to check your email to verify your account
        </p>
        <a href="{{route('send.verify')}}">Send new verification mail</a>
    </div>

    {{-- Alert Card End --}}

</div>

<!-- Content End -->
@endsection

@push('Javascript')

@endpush