routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use App\Http\Controllers\Wall\WallController as Wall;
use App\Http\Controllers\Wall\NewsController as News;
use App\Http\Controllers\Account\AuthenticationController as Authentication;
use App\Http\Controllers\Account\AccountController as Account;
use App\Mail\VerifyAccount;
use App\Models\User;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middleware' => 'verifyingAccount'], function() {

    Route::resource('/', Wall::class);

    Route::resource('/news', News::class);

    Route::get('/profile', [Account::class, 'indexProfile'])->name('profile');

    Route::put('/profile-edit', [Account::class, 'updateProfile'])->name('update.profile');

});

Route::group(['prefix' => '/register', 'middleware' => 'guest'], function() {

    Route::get('/', [Authentication::class, 'indexRegister'])->name('register');

    Route::post('/', [Authentication::class, 'register'])->name('register.store');

});

Route::group(['prefix' => '/login', 'middleware' => 'guest'], function() {

    Route::get('/', [Authentication::class, 'indexLogin'])->name('login');

    Route::post('/', [Authentication::class, 'login'])->name('login.store');

});

Route::group(['middleware' => 'auth'], function() {
    
    Route::get('/verifying-account', function() {
        if (Auth::user()->verified_at == null) {
            return view('Apps.Public.Account.VerifyingAccount');
        } else {
            return redirect()->route('index');
        }
        
    })->name('verifying-account');

    Route::get('/send-verify', function() {
        $email    = Auth::user()->email;
        $username = Auth::user()->username;
        Mail::to($email)->send(new VerifyAccount($username, $email));
        return redirect()->route('verifying-account');
    })->name('send.verify');

    Route::get('/token={token}', function($token) {
        if (Auth::user()->token_verification == $token) {
            User::find(Auth::id())->update([
                'verified_at' => date("Y-m-d H:i:s"),
            ]);
            return redirect()->route('index');
        }
    });

    Route::get('/logout', function() {
        Auth::logout();
        return redirect()->route('index');
    })->name('logout');

});

resources/views/Layouts/Public/Footer.blade.php
<!-- Foot -->

<div class="foot" style="background-color: rgb(97, 97, 97);">
    <div class="raw padd5">
        <div class="cal6">
            <p class="t-white t-size4 t-center">about</p>
            <div class="divider-white" style="background-color:white;"></div>
            <p class="t-white"><span class="t-size3">8-Site</span> Blog for Writer, Simpler and Easier to use. More
                Feature is <span class="t-size3">Coming Soon</span></p>
        </div>

        <div class="cal6">
            <p class="t-white t-size4 t-center">contact</p>
            <div class="divider-white" style="background-color:white;"></div>
            <ul class="foot-list">
                <li>
                    <a href="https://www.instagram.com/ricky_tiaka/" class="t-white">
                        <i class="fi-xnsuxm-instagram"></i>
                        @ricky_tiaka
                    </a>
                </li>
                <li>
                    <a href="https://www.facebook.com/RickyCaesarAprillaTiaka/" class="t-white">
                        <i class="fi-xnsuxm-facebook-logo"></i>
                        @ricky_tiaka
                    </a>
                </li>
                <ul>
        </div>
    </div>

    <div class="foot-down t-white">
        &copy; RDev Project 2020-2021
    </div>
</div>

<!-- Foot End -->
</body>
</html>
<!-- Friconix https://friconix.com-->
<script src="{{asset('Assets/friconix.js')}}"></script>
<script src="{{asset('Assets/rdev.min.js')}}"></script>

resources/views/Layouts/Public/Header.blade.php
<!-- 
     Valv3.exe ~ Ricky Caesar Aprilla Tiaka
     rickycaesar6402@gmail.com
    ...- .- .-.. ...- ...-- .-.-.- . -..- . / -...- / .-. .. -.-. -.- -.-- / -.-. .- . ... .- .-. / .- .--. .-. .. .-.. .-.. .- / - .. .- -.- .- .-.-.- / .-. .. -.-. -.- -.-- -.-. .- . ... .- .-. -.... ....- ----- ..--- .--.-. --. -- .- .. .-.. .-.-.- -.-. --- --
-->
<!DOCTYPE html>
<html>

<head>
    <title>{{env('APP_NAME')}}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- asset -->

    <link rel="stylesheet" href="{{asset('Assets/rdev.min.css')}}">
    <link rel="stylesheet" href="asset/custom.css">

    <!-- asset end -->
</head>

<body onmousewheel="autoNav()" class="body">

    <!-- Navbar -->

    <nav id="main-navbang" class="navbang" style="background-color: gainsboro;">
        <a href="{{route('index')}}" class="navbang-title title-black marg1">
            8-Site
        </a>
        <ul class="navbang-link link-black t-size2 margauto-r">
            @if (Auth::check()&&Auth::user()->verified_at != null)
            <li>
                <a href="{{route('index')}}">
                    Home
                </a>
            </li>
            <li>
                <a href="{{route('news.index')}}">
                    News
                </a>
            </li>
            @endif
        </ul>
        <ul class="navbang-link link-black t-size2 marg1-r">
            @if (Auth::check())
            @if (Auth::user()->verified_at != null)
            <li>
                <a href="{{route('profile')}}">
                    Account
                </a>
            </li>
            @endif
            <li>
                <a onclick="return confirm('Are your really want logout?')" href="{{route('logout')}}">
                    Logout
                </a>
            </li>
            @else
            <li>
                <a href="{{route('index')}}">
                    Login
                </a>
            </li>
            <li>
                <a href="{{route('register')}}">
                    Register
                </a>
            </li>
            @endif
        </ul>

    </nav>

    <!-- Navbar end -->

    <!-- Navbar Fixed -->
    <nav id="second-navbang" class="fixed-navbang" style="background-color: gainsboro;">
        <a href="{{route('index')}}" class="navbang-title title-black marg1">
            8-Site
        </a>
        <ul class="navbang-link link-black t-size2 margauto-r">
            @if (Auth::check()&&Auth::user()->verified_at != null)
            <li>
                <a href="{{route('index')}}">
                    Home
                </a>
            </li>
            <li>
                <a href="{{route('news.index')}}">
                    News
                </a>
            </li>
            @endif
        </ul>
        <ul class="navbang-link link-black t-size2 marg1-r">
            @if (Auth::check())
            @if (Auth::user()->verified_at != null)
            <li>
                <a href="{{route('profile')}}">
                    Account
                </a>
            </li>
            @endif
            <li>
                <a onclick="return confirm('Are your really want logout?')" href="{{route('logout')}}">
                    Logout
                </a>
            </li>
            @else
            <li>
                <a href="{{route('index')}}">
                    Login
                </a>
            </li>
            <li>
                <a href="{{route('register')}}">
                    Register
                </a>
            </li>
            @endif
        </ul>
    </nav>
    <!-- Navbar Fixed end -->

    <!-- Navbar Responsive -->

    <div id="bg" onclick="closeNav()"></div>
    <button id="openNav" type="button" class="btn-respon-black" onclick="openNav()">
        <i class="fi-xnsuxm-plus-solid"></i>
    </button>

    <nav id="navbang-respon" class="navbang-respon">
        <a href="{{route('profile')}}"
            class="navbang-title-respon img-size1 img-circ img-center img-prof marg4-t marg4-b"
            style="background-image: url({{asset('Storage/Image/Ricky.png')}});">
        </a>
        <ul class="navbang-link-respon">
            @if (Auth::check()&&Auth::user()->verified_at != null)
            <li>
                <a href="{{route('index')}}">
                    Home
                </a>
            </li>
            <li>
                <a href="{{route('news.index')}}">
                    News
                </a>
            </li>
            @endif
            @if (Auth::check())
            <li>
                <a onclick="return confirm('Are your really want logout?')" href="{{route('logout')}}">
                    Logout
                </a>
            </li>
            @else
            <li>
                <a href="{{route('index')}}">
                    Login
                </a>
            </li>
            <li>
                <a href="{{route('register')}}">
                    Register
                </a>
            </li>
            @endif
        </ul>
    </nav>

    <!-- Navbar Responsive end -->

resources/views/Layouts/Public/Master.blade.php
@include('Layouts.Public.Header')
@yield('Content')
@include('Layouts.Public.Footer')
@stack('Javascript')