routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use App\Http\Controllers\Wall\WallController as Wall;
use App\Http\Controllers\Wall\NewsController as News;
use App\Http\Controllers\Account\AuthenticationController as Authentication;
use App\Http\Controllers\Account\AccountController as Account;
use App\Mail\VerifyAccount;
use App\Models\User;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middleware' => 'verifyingAccount'], function() {

    Route::resource('/', Wall::class);

    Route::resource('/news', News::class);

    Route::get('/profile', [Account::class, 'indexProfile'])->name('profile');

    Route::put('/profile-edit', [Account::class, 'updateProfile'])->name('update.profile');

});

Route::group(['prefix' => '/register', 'middleware' => 'guest'], function() {

    Route::get('/', [Authentication::class, 'indexRegister'])->name('register');

    Route::post('/', [Authentication::class, 'register'])->name('register.store');

});

Route::group(['prefix' => '/login', 'middleware' => 'guest'], function() {

    Route::get('/', [Authentication::class, 'indexLogin'])->name('login');

    Route::post('/', [Authentication::class, 'login'])->name('login.store');

});

Route::group(['middleware' => 'auth'], function() {
    
    Route::get('/verifying-account', function() {
        if (Auth::user()->verified_at == null) {
            return view('Apps.Public.Account.VerifyingAccount');
        } else {
            return redirect()->route('index');
        }
        
    })->name('verifying-account');

    Route::get('/send-verify', function() {
        $email    = Auth::user()->email;
        $username = Auth::user()->username;
        Mail::to($email)->send(new VerifyAccount($username, $email));
        return redirect()->route('verifying-account');
    })->name('send.verify');

    Route::get('/token={token}', function($token) {
        if (Auth::user()->token_verification == $token) {
            User::find(Auth::id())->update([
                'verified_at' => date("Y-m-d H:i:s"),
            ]);
            return redirect()->route('index');
        }
    });

    Route::get('/logout', function() {
        Auth::logout();
        return redirect()->route('index');
    })->name('logout');

});

app/Http/Controllers/Wall/NewsController.php
<?php

namespace App\Http\Controllers\Wall;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

use Auth;
use Str;
use Storage;
use App\Models\Posts;

class NewsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('Apps.Public.News.Index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('Apps.Public.Post.Post');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'thumbnail' => 'required|image',
            'title' => 'required',
            'content' => 'required',
        ]);

        $title = $request->title;
        $content = $request->content;
        $slug = Str::slug($title, '-');
        $author = Auth::id();
        $thumbnail = $request->thumbnail;
        $thumbnail_name = '8_site'.date('Y-m-d-H-i-s').'.png';

        Posts::create([
            'thumbnail' => $thumbnail_name,
            'title' => $title,
            'content' => $content,
            'slug' => $slug,
            'author' => $author,
        ]);

        Storage::disk('storage')->putFileAs('Image', $thumbnail, $thumbnail_name);

        return redirect()->route('news.show', $slug);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($slug)
    {
        $news = Posts::where('slug', $slug)->first();
        return view('Apps.Public.News.Detail_Post', ['news' => $news]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $slug_old)
    {
        $this->validate($request, [
            'thumbnail' => 'image',
            'title' => 'required',
            'content' => 'required',
        ]);

        $title = $request->title;
        $content = $request->content;
        $slug = Str::slug($title, '-');
        $author = Auth::id();
        $thumbnail = $request->thumbnail;
        $thumbnail_name = '8_site'.date('Y-m-d-H-i-s').'.png';

        $News = Posts::where('slug', $slug_old);

        if ($request->hasfile('thumbnail')) {
            Storage::delete($request->thumbnail);
            Storage::disk('storage')->putFileAs('Image', $thumbnail, $thumbnail_name);
            $News->update([
                'thumbnail' => $thumbnail_name,
            ]);
        }

        $News->update([
            'title' => $title,
            'content' => $content,
            'slug' => $slug,
        ]);

        return redirect()->route('news.show', $slug);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($uuid)
    {
        Posts::findOrFail($uuid)->delete();
        return redirect()->route('profile');
    }
}

resources/views/Apps/Public/News/Detail_Post.blade.php
@extends('Layouts.Public.Master')

@section('Content')
<!-- Content -->

<div class="gap">
    <div class="raw">
        <div class="cal9 padd1">
            <div id="contentField">
                <div class="group-form padd1-b">
                    <h1>{{$news->title}}</h1>
                </div>
                <div class="divider-black"></div>
                <img class="img-roun img-center" style="width: 60%;" src="{{asset('Storage/Image/'.$news->thumbnail)}}" alt="">
                <div class="field-white marg1 padd1">
                    {!!$news->content!!}
                </div>
            </div>
            <form id="editform" action="{{route('news.update', ['news'=>$news->slug])}}" method="POST" enctype="multipart/form-data"
                style="display: none;">
                @csrf
                @method('PUT')
                <div class="group-form padd1-b">
                    <input id="title" name="title" type="text" placeholder="Title" value="{{$news->title}}">
                </div>
                <div class="group-form padd1-b">
                    <input id="thumbnail" name="thumbnail" type="file" placeholder="Thumbnail" accept="image/*">
                </div>
                <div id="content" class="field-white marg1 padd1">
                    {!!$news->content!!}
                </div>
                <button class="btn btn-grass btn-box t-size2" type="submit">Post</button>
                <button class="btn btn-lava btn-box t-size2" type="button" onclick="CloseEditForm()">Close</button>
            </form>
            <div class="raw">
                <div class="cal12 t-right">
                    <i>{{$news->created_at->diffForHumans()}} By {{$news->Author->username}}</i>
                </div>
            </div>
            @if ($news->author == Auth::id())
            <button id="edit" class="btn btn-grass btn-box t-size2" type="button" onclick="EditForm()">Edit</button>
            @endif
        </div>
        <div class="calauto raw padd1-t padd1-b">
            <div class="cal12">
                <div class="card-box">
                    <div class="card-box-body-black no-img">
                        <p class="t-size4 t-center t-white">News</p>
                    </div>
                </div>
            </div>
            @foreach (RDev::SideNews($news->slug) as $sidenews)
            <div class="cal12">
                <div class="card-box">
                    <a href="">
                        <div class="card-image" style="background-image: url({{asset('Storage/Image/'.$sidenews->thumbnail)}});"></div>
                    </a>
                    <div class="card-box-body-white with-img">
                        <div class="card-title">
                            <a href="{{route('news.show', [$sidenews->slug])}}" class="t-size3 t-black">{{$sidenews->title}}</a>
                        </div>
                        <p class="t-black t-center">
                            {!!$sidenews->content!!}
                        </p>
                        <div class="raw t-size1">
                            <div class="cal5 t-left">
                                <p class="t-black">{{$sidenews->created_at->diffForHumans()}} by {{$sidenews->Author->username}}</p>
                            </div>
                            <div class="cal7 t-right">
                                <a href="{{route('news.show', [$sidenews->slug])}}" class="t-black">Baca Selengkapnya</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>   
            @endforeach
        </div>
    </div>
</div>
<!-- Content End -->
@endsection

@push('Javascript')
<script src="https://cdn.tiny.cloud/1/6b8uaskbm3fqridpjj1g35bn0jztbapikon6k5fqwu1861ed/tinymce/5/tinymce.min.js"
    referrerpolicy="origin"></script>
<script>
    function EditForm() {
        document.getElementById("contentField").style.display = "none"
        document.getElementById("editform").style.display = "block"
        document.getElementById("edit").style.display = "none"
    }

    function CloseEditForm() {
        document.getElementById("contentField").style.display = "block"
        document.getElementById("editform").style.display = "none"
        document.getElementById("edit").style.display = "block"
    }
</script>
<script>
    tinymce.init({
        selector: '#content',
        inline: true,
        toolbar_mode: 'sliding',
        toolbar_location: 'bottom',
        menubar: 'false',
        toolbar: 'undo redo | formatselect | alignleft aligncenter alignright alignjustify | image link | forecolor backcolor fontsizeselect bold italic strikethrough underline hr | outdent indent table codesample emoticons',
        plugins: [
            "image autolink codesample emoticons hr help link table wordcount"
        ],
        // and here's our custom image picker
        file_picker_callback: function (cb, value, meta) {
            var input = document.createElement('input');
            input.setAttribute('type', 'file');
            input.setAttribute('accept', 'image/*');
            // Note: In modern browsers input[type="file"] is functional without 
            // even adding it to the DOM, but that might not be the case in some older
            // or quirky browsers like IE, so you might want to add it to the DOM
            // just in case, and visually hide it. And do not forget do remove it
            // once you do not need it anymore.

            input.onchange = function () {
                var file = this.files[0];

                var reader = new FileReader();
                reader.onload = function () {
                    // Note: Now we need to register the blob in TinyMCEs image blob
                    // registry. In the next release this part hopefully won't be
                    // necessary, as we are looking to handle it internally.
                    var id = 'blobid' + (new Date()).getTime();
                    var blobCache = tinymce.activeEditor.editorUpload.blobCache;
                    var base64 = reader.result.split(',')[1];
                    var blobInfo = blobCache.create(id, file, base64);
                    blobCache.add(blobInfo);

                    // call the callback and populate the Title field with the file name
                    cb(blobInfo.blobUri(), {
                        title: file.name
                    });
                };
                reader.readAsDataURL(file);
            };
            input.click();
        }
    });
</script>
@endpush

resources/views/Apps/Public/News/Index.blade.php
@extends('Layouts.Public.Master')
@section('Content')
<!-- Content -->

<div class="gap">
    <!-- Slider -->

    <div>
        @if (RDev::CountPost() != 0)
        @foreach (RDev::Slider('slider') as $slider)
        <div class="banner banner-box banner-title-bg slider"
            style="background-image: url({{asset('Storage/Image/'.$slider->thumbnail)}})">
            <div class="raw">
                <div class="cal4 banner-title">
                    <p>{{$slider->title}}</p>
                </div>
            </div>

            <div class="raw marg1 marg4-t just-end">
                <div class="cal6 banner-content">
                    <p>{{$slider->title}}</p>
                    <div class="divider-white"></div>
                    <div class="t-left">
                        <i class="t-size1">{{$slider->created_at->diffForHumans()}} By {{$slider->Author->username}}</i>
                    </div>
                    <div class="marg2-t">
                        <a href="{{route('news.show', [$slider->slug])}}"><button class="btn btn-grass btn-box">Baca Selengkapnya</button></a>
                    </div>
                </div>
            </div>
        </div>
        @endforeach
        {!!RDev::Slider('btnSlider')!!}
        @endif
    </div>


    <!-- Slider End -->
    <div class="marg2-t marg2-b">
        <div class="raw">
            @foreach (RDev::News(8) as $news)
            <div class="cal3">
                <div class="card-box">
                    <a href="{{route('news.show', [$news->slug])}}">
                        <div class="card-image"
                            style="background-image: url({{asset('Storage/Image/'.$news->thumbnail)}});"></div>
                    </a>
                    <div class="card-box-body-white with-img">
                        <div class="card-title">
                            <a href="{{route('news.show', [$news->slug])}}" class="t-size3 t-black">{{$news->title}}</a>
                        </div>
                        <p class="t-black" href="">
                            {{$news->title}}
                        </p>
                        <div class="raw t-size1">
                            <div class="cal5 t-left">
                                <p class="t-black">{{$news->created_at->diffForHumans()}}</a>
                            </div>
                            <div class="cal7 t-right">
                                <a href="{{route('news.show', [$news->slug])}}" class="t-black">Baca Selengkapnya</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            @endforeach
        </div>
    </div>
</div>

{{RDev::News(8)->links('vendor.pagination.bootstrap-4')}}
</div>

<!-- Content End -->
@endsection

@push('Javascript')

@endpush