routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use App\Http\Controllers\Wall\WallController as Wall;
use App\Http\Controllers\Wall\NewsController as News;
use App\Http\Controllers\Account\AuthenticationController as Authentication;
use App\Http\Controllers\Account\AccountController as Account;
use App\Mail\VerifyAccount;
use App\Models\User;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middleware' => 'verifyingAccount'], function() {

    Route::resource('/', Wall::class);

    Route::resource('/news', News::class);

    Route::get('/profile', [Account::class, 'indexProfile'])->name('profile');

    Route::put('/profile-edit', [Account::class, 'updateProfile'])->name('update.profile');

});

Route::group(['prefix' => '/register', 'middleware' => 'guest'], function() {

    Route::get('/', [Authentication::class, 'indexRegister'])->name('register');

    Route::post('/', [Authentication::class, 'register'])->name('register.store');

});

Route::group(['prefix' => '/login', 'middleware' => 'guest'], function() {

    Route::get('/', [Authentication::class, 'indexLogin'])->name('login');

    Route::post('/', [Authentication::class, 'login'])->name('login.store');

});

Route::group(['middleware' => 'auth'], function() {
    
    Route::get('/verifying-account', function() {
        if (Auth::user()->verified_at == null) {
            return view('Apps.Public.Account.VerifyingAccount');
        } else {
            return redirect()->route('index');
        }
        
    })->name('verifying-account');

    Route::get('/send-verify', function() {
        $email    = Auth::user()->email;
        $username = Auth::user()->username;
        Mail::to($email)->send(new VerifyAccount($username, $email));
        return redirect()->route('verifying-account');
    })->name('send.verify');

    Route::get('/token={token}', function($token) {
        if (Auth::user()->token_verification == $token) {
            User::find(Auth::id())->update([
                'verified_at' => date("Y-m-d H:i:s"),
            ]);
            return redirect()->route('index');
        }
    });

    Route::get('/logout', function() {
        Auth::logout();
        return redirect()->route('index');
    })->name('logout');

});

app/Models/Posts.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Notifications\Notifiable;

use App\Traits\Uuid;

class Posts extends Model
{
    use Uuid;

    use HasFactory, Notifiable;

    protected $table = 'posts';

    protected $primaryKey = 'uuid';

    public $incrementing = false;

    protected $keyType = 'string';

    public $timestamps = true;

    protected $fillable = [
        'thumbnail',
        'title',
        'content',
        'slug',
        'author',
    ];

    public function Author()
    {
        return $this->belongsTo('App\Models\User', 'author', 'uuid');
    }
}

resources/views/Apps/Public/Post/Post.blade.php
@extends('Layouts.Public.Master')

@section('Content')
<!-- Content -->
@if ($errors->any())
    <div class="card-alert-lava marg2-t">
        @foreach ($errors->all() as $error)
            <li>{{ $error }}</li>
        @endforeach
    </div>
@endif
<div class="gap">
    <div class="raw">
        <div class="cal9 padd1">
            <form action="{{route('news.store')}}" method="POST" enctype="multipart/form-data">
                @csrf
                <div class="group-form padd1-b">
                    <input id="title" name="title" type="text" placeholder="Title">
                </div>
                <div class="group-form padd1-b">
                    <input id="thumbnail" name="thumbnail" type="file" placeholder="Thumbnail" accept="image/*">
                </div>
                <div id="content" class="field-white marg1 padd1">
                    Content Here
                </div>
                <button class="btn btn-grass btn-box t-size2" type="submit">Post</button>
            </form>
        </div>
    </div>
</div>
<!-- Content End -->
@endsection

@push('Javascript')
<script src="https://cdn.tiny.cloud/1/6b8uaskbm3fqridpjj1g35bn0jztbapikon6k5fqwu1861ed/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
<script>
    tinymce.init({
    selector: '#content',
    inline: true,
    toolbar_mode: 'sliding',
    toolbar_location: 'bottom',
    menubar : 'false',
    toolbar: 'undo redo | formatselect | alignleft aligncenter alignright alignjustify | image link | forecolor backcolor fontsizeselect bold italic strikethrough underline hr | outdent indent table codesample emoticons',
    plugins: [
                "image autolink codesample emoticons hr help link table wordcount"
            ],
    // and here's our custom image picker
    file_picker_callback: function (cb, value, meta) {
                var input = document.createElement('input');
                input.setAttribute('type', 'file');
                input.setAttribute('accept', 'image/*');
                // Note: In modern browsers input[type="file"] is functional without 
                // even adding it to the DOM, but that might not be the case in some older
                // or quirky browsers like IE, so you might want to add it to the DOM
                // just in case, and visually hide it. And do not forget do remove it
                // once you do not need it anymore.

                input.onchange = function () {
                    var file = this.files[0];

                    var reader = new FileReader();
                    reader.onload = function () {
                        // Note: Now we need to register the blob in TinyMCEs image blob
                        // registry. In the next release this part hopefully won't be
                        // necessary, as we are looking to handle it internally.
                        var id = 'blobid' + (new Date()).getTime();
                        var blobCache = tinymce.activeEditor.editorUpload.blobCache;
                        var base64 = reader.result.split(',')[1];
                        var blobInfo = blobCache.create(id, file, base64);
                        blobCache.add(blobInfo);

                        // call the callback and populate the Title field with the file name
                        cb(blobInfo.blobUri(), {
                            title: file.name
                        });
                    };
                    reader.readAsDataURL(file);
                };
                input.click();
            }
  });
</script>
@endpush